# Site
repository: yoelsheikh/yoelsheikh.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Yousif M. Elsheikh 
title: Kaisersautern, Germany
email: yoelsheikh@gmail.com
# email_title: Email (Email title override)
phone: +49-152-17278662
# phone_title: Phone (Phone title override)
# website: https://yoelsheikh.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  yoelsheikh
linkedin_username: yousif-m-elsheikh-


# Additional icon links.... remove #### with no ident, edit as described
##### additional_links:
#####- title: Link name
#####  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#####  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"
# ###regular resume download button # [Download my resumé here](https://github.com/YoElsheikh/yoelsheikh.github.io/raw/master/_pdfs/resume.pdf){: .btn .btn--info .btn--large}

# About Section
about_title: Bio       
about_profile_image: /images/pp.jpg
about_content: | # this will include new lines to allow paragraphs
       Hello! I am Yousif, a mechanical engineer at heart with a passion for robotics. My master's thesis at the Robotics Research Lab focused on leveraging
       Unreal Engine for SIL (Simulation-in-the-Loop) based training of RL agents using various sensor modalities and reward tuning 
       with the aim of achieving meaningful sim2real transfer. The developed training scheme is highly reusable. 
       My interests include 3D Computer Vision, Deep Learning, Control Theory/Dynamical Systems and Reinforcement Learning.
       I enjoy long walks and ample coffee.

       Download resumé: <span style="margin-right: 20px;"></span>
       <a href="https://raw.githubusercontent.com/YoElsheikh/yoelsheikh.github.io/master/_pdfs/lebenslauf.pdf" target="_blank" title="in German">
       <i class="fa fa-file-pdf-o"></i> in German
       </a>
       <span style="margin-right: 35px;"></span>
       <a href="https://raw.githubusercontent.com/YoElsheikh/yoelsheikh.github.io/master/_pdfs/resume.pdf" target="_blank" title="in English">
       <i class="fa fa-file-pdf-o"></i> in English
       </a>

       



content:
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Technische Universität Kaiserslautern
        sub_title: Master of Science in Vehicle Engineering 
        caption: 2023
        quote: >
         Thesis: Reinforcement Learning on Sensor Data and Reaction Grid Maps, AG Robotersysteme 
        description: | # this will include new lines to allow paragraphs
         Focus: Autonomous Mobile Robots, Embedded Intelligence, C++ Programming Project, Robot and Motion Control, Robust Control, Design of Human-Machine Systems, Seminar Electromobility
      - layout: top-right
        title: University of Khartoum 
        sub_title: Bachelor of Science in Mechanical Engineering 
        caption: 2016
        quote: >
          Thesis: Comparative Study between Conventional Controllers for the Inverted Pendulum Automobil 
        description: | # this will include new lines to allow paragraphs        
  
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: YOLOv7-Cutter for Pet Detection 
        link: https://www.adam-riese.de/hundehalter/antrag/start
        link_text: Link to HHV-Tool (live as of 28.08.2023)
        additional_links:
          - title:  https://www.adam-riese.de/hundehalter/antrag/start
            icon: fab fa-globe fa-lg
            url: https://www.adam-riese.de/hundehalter/antrag/start
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
           # icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Pytorch | Tensorflow | Linux | Transfer Learning | Computer Vision | Docker | ONNX
        description: | # this will include new lines to allow paragraphs
          Migration from YOLOv3 + Keras runtime to YOLOv7 + ONNX runtime, modifying the pipeline for better performance. Training and detailed evaluation
          and comparison between the 2 pipelines. Deployment.
          *Accomplishments*: Labeled Training data, trained YOLOv7 and carried out a detailed evaluation to consolidate the increase of performance
          (accuracy, precision & recall) beteween the old and new pipeline. The tool is live as of 28.08.2023.
          
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: PoC of a 3D Computer Vision Pipeline Applied to a Logistics Robot Manipulator 
        additional_links:
          - title:  Githup page for the highlights
            icon: fab fa-github fa-lg
            url: https://github.com/YoElsheikh/realsense-python-ergeb
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
           # icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Pytorch | Tensorflow | Intel RealSense | Transfer Learning | Signal Processing | ROS | Docker | Linux
        description: | # this will include new lines to allow paragraphs
          Proof of Concept and Know-How using Stereo-vision generated data and Deep Learning to position and classify objects 
          for a logistic-arm manipulator. Dataset generation, labeling and best approach investigation.
          *Accomplishments*: Applied and modified 2 state-of-the-art 3D CV class algorithms, one that consumes pointclouds directly 
          as well as techniques that are based on 2D CV and leverages pointclouds to estimate the position.
    # layout: list # Type of content section (list/text)
    # content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: iterative LQR applied to Simple Robot Dynamics
        additional_links:
          - title:  arXiv link
            icon: fa fa-file-pdf-o fa-lg 
            url: https://arxiv.org/pdf/2404.18312
        quote: >
          MATLAB | Control Theory | Optimal Control | Optimization | Modelling | Git
        description: | # this will include new lines to allow paragraphs
          Application of the iterative linear quadratic regulator for path tracking for a simple model of a mobile robot.
          *Accomplishments*: Successfully applied the controller, which is the first of its kind in the chair for Electromobility at TU Kaiserslautern
          securing a 1,0.
      - layout: left
        border:   # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Genetic-Algorithm-based Optimal Control of the Inverted Pendulum System 
        additional_links:
        quote: >
         Mathematical Modelling | MATLAB | Control Theory | Optimal Control | Optimization | Genetic Algorithm | IPS
        description: | # this will include new lines to allow paragraphs
          Detailed mathematical modelling of the IPS (Inverted Pendulum System) and leveraging the Genetic Algorithm to determine the components that
          minimize the cost function of the LQR to stabalize the non-linear IPS.
          *Accomplishments*: Successfully applied the controller and carried out a comparison against fine-tuned LQR considering the performance and energy
          consumption.                  
  - title: Experience
    layout: list
    content:
      - layout: right
        title: IPG Automotive GmbH, Karlsruhe DE
        sub_title: Working Student
        caption: Dec 2023 - Now
        link: www.ipg-automotive.com/en
        quote: >
        description: | # this will include new lines to allow paragraphs
              Development and implementation of SIL-based V2X communicaiton such as Collective Perception Message (CPM) according to European standards in the simulation software CarMaker, 
              using C-code for variable calculation.
              Responsible for extending and version control of the V2X interface in collaboration with the development team.
      - layout: right
        title: Adam Riese GmbH, Stuttgart DE
        sub_title: Working Student
        caption: Nov 2022 - Sep 2023
        link: 
        quote: >
        description: | # this will include new lines to allow paragraphs
              Deployment of an object-detection algorithm, including labling, Transfer Learning, training and evaluation of the algorithm as well as the pipeline
              in which the algorithm is deployed (in ONNX-Runtime). 
      - layout: right
        title: Würth Industrie Service Gmbh & Co. KG, Bad Mergentheim DE
        sub_title: Intern
        caption: Mar 2022 - Sep 2022
        link: wuerth-industrie.com
        quote: >
        description: | # this will include new lines to allow paragraphs
              Literature research, development and application of 3D computer vision state-of-the-art techniques for object recognition and position determination for a robotic manipulator.
              Data generation, labeling and training to learn patterns and position from point cloud data.
      - layout: right
        title: Technische Universität Kaiserslautern, Kaiserslautern DE
        sub_title: Student Assistant 
        caption: Aug 2021 - Mar 2022
        link: uni-kl.de
        quote: >
        description: | # this will include new lines to allow paragraphs
            **RRLab (Robotics Research Lab)**: Literature research, dataset generation (video/images) for underwater object recognition from Forward Looking Sonar data. 
              Research mosaicing, and mapping of the underwater environment and deployment of image processing algorithms. Experimantal verification of algorithms.   
             **Department of Mechanical and Process Engineering**: Use road features (from GPR sensor data) leveraging GANs and CGANs to create subsurface
              road cracks according to type.
      - layout: right
        title: Hi-Force Engineering Works, Khartoum SD 
        sub_title: Design Engineer 
        caption: Aug 2018 - Feb 2019
        link: hiforce.sudatum.com
        quote: >
        description: | # this will include new lines to allow paragraphs
            Perform conceptual design of components and implement design improvements using 3D Modeling tools to reduce cost and improve functionality.
            Conduct market research and design standardization.
      - layout: right
        title: University of Khartoum, Khartoum SD 
        sub_title: Teaching Assistant 
        caption: Dec 2016 - Dec 2017
        link: eng.uofk.edu/en/
        quote: >
        description: | # this will include new lines to allow paragraphs
              Reinforce and manage lectures in the subjects:
              "Fluid Mechanics I", "Computer Applications", "Measurement and Instrumentation", "Gas Dynamics"
              and "Hydraulics & Pneumatic Power Transmission".    
     
  - title: Other
    layout: text
    content: | # this will include new lines to allow paragraphs
     **Skills** Research • Simulation • Machine Learning • Reinforcement Learning • Computer Vision • Deep Learning • Autonomous Driving • Linux •
     Unreal Engine • Docker • C/C++ • Python (Stable Baselines, conda, PyTorch, Tensorflow, Keras, Open3D, Pandas, NumPy) • Git •
     ROS/2 • Finroc • OpenCV • CAD (SolidWorks, MATLAB + Simulink) • MS Office Suite • MS Visual Studio/VS Code.
     **Languages**
     I Speak Arabic, English and German fluently. *Related language examinations*: DSH 2; from LMU München & TU Kaiserslautern, IELTS.
          
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
